### ISSUE TITLE
Google Maps API Key permissions

### ISSUE THREAD

**Issue by ben-var** [MCC-CSClub/mcc-csclub.github.io#17]
The API key needs to have the following urls added to its permissions:

1. http://mcc-csclub.github.io/*
2. https://mcc-csclub.github.io/*

the * is a wildcard character that allows any url after it. Without this, the google applet breaks when 
you refer to a #section of the site.

**Comment by NoahT** [comment]
Added just now. Thanks

**Comment by ben-var** [comment]
Gracias!
