### ISSUE TITLE
Update links

### ISSUE THREAD

**Issue by ChristopherWMM** [MCC-CSClub/mcc-csclub.github.io#26]
Many of the links on the site (GitHub specifically) don't go anywhere. This should be a priority to make sure we are directing people to the right place.

**Comment by rajenr** [comment]
There is a lot of work to do regarding this issue, because we must also update the Projects section (more specifically, incorporate links to the newer repos). One of the links under the Club Leadership section is newly broken, as well.

**Comment by Headline** [comment]
With the incoming transition and reworks, this is now stale.
